[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "build123notebooks"
version = "0.0.1"
requires-python = ">=3.11"

dependencies = ["build123d", "ipykernel"]

[tool.setuptools]
py-modules = []
